yarn task deploy:factory $1
yarn task status $1
yarn task model:create $1
yarn task model:populate $1
yarn task deploy:contents $1
yarn task types:add $1
yarn task subscription:buy $1
yarn task subscription:active $1
yarn task users:manage $1
yarn task users:drop $1